const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),{JSDOM}=require('jsdom');
const signs=require('../private-membership/service').signs;
const content={General:'Full Moon boundary scripts — keep exactly',...Object.fromEntries(signs.map(s=>[s,s+' forecast']))};
const months=[{month:'2026-10',title:'October 2026 Horoscopes',subtitle:'October subtitle',published_at:'2026-09-21T15:00:00Z',published:content,content,draft:content,revision:1},{month:'2026-09',title:'Full Moon boundary scripts',featured_at:'2026-09-24T00:00:00Z',published_at:'2026-09-21T15:00:00Z',published:content,content,draft:content,revision:1},{month:'2099-01',title:'Demonstration month',demo:true,content}];
async function member(path,rows=months){const d=new JSDOM('<main id="app"></main><p id="feedback"></p>',{url:'https://lucehealing.com'+path,runScripts:'outside-only'});d.window.HTMLElement.prototype.scrollIntoView=function(){};d.window.fetch=async u=>({ok:true,json:async()=>u.endsWith('/config')?{signs}:u.endsWith('/me')?{access:true}:u.includes('/reading?')?{groups:[{sign:'Aries',placements:[],content:'Personal Aries forecast'}]}:rows});d.window.eval(fs.readFileSync('private-membership/member.js','utf8'));await new Promise(r=>setTimeout(r,20));return d;}
test('explicit featured month wins, archive buttons open older collections, titles hide technical labels',async()=>{
 const d=await member('/members'),doc=d.window.document;try{assert.equal(doc.querySelector('#month-label').textContent,'Full Moon boundary scripts');assert.match(doc.body.textContent,/Previous Months/);assert.doesNotMatch(doc.body.textContent,/2026-10|2026-09|Demonstration|2099/);await doc.querySelector('[data-open-month="2026-10"]').onclick({preventDefault(){}});assert.equal(doc.querySelector('#month-label').textContent,'October 2026 Horoscopes');assert.equal(doc.querySelector('#month-subtitle').textContent,'October subtitle');assert.equal(doc.querySelectorAll('#readings details').length,13);}finally{d.window.close();}
});
test('future month opens immediately with no featured override and old links still work',async()=>{const rows=months.slice(0,2).map(m=>({...m,featured_at:null}));let d=await member('/members',rows);assert.equal(d.window.document.querySelector('#month-label').textContent,'October 2026 Horoscopes');d.window.close();d=await member('/members?month=2026-09',rows);assert.equal(d.window.document.querySelector('#month-label').textContent,'Full Moon boundary scripts');d.window.close();});
test('personal reading uses the selected featured collection and preserved endpoint',async()=>{const d=await member('/members/reading');assert.match(d.window.document.querySelector('#readings').textContent,/Personal Aries forecast/);d.window.close();});
test('metadata-only Admin save excludes content and retains unsaved editor text',async()=>{
 const d=new JSDOM('<div data-membership-admin></div>',{url:'https://lucehealing.com',runScripts:'outside-only'});d.window.HTMLElement.prototype.scrollIntoView=function(){};let rows=structuredClone(months.slice(0,2)),payload;
 d.window.fetch=async(url,opts)=>{let result;if(opts.method==='PATCH'){payload=JSON.parse(opts.body);rows[0]={...rows[0],...payload,revision:2};result=rows[0];}else result=url.includes('/status?')?{}:url.includes('/members?')?[]:rows;return {ok:true,json:async()=>result};};
 try{d.window.eval(fs.readFileSync('membership-admin.js','utf8'));await d.window.loadMembershipAdmin();const doc=d.window.document;doc.querySelector('[data-open-month="2026-10"]').click();assert.equal(doc.querySelector('#mb-month').disabled,false);assert.equal(doc.querySelector('#mb-status').value,'published');doc.querySelector('#mb-General').value='Unsaved reading edits';doc.querySelector('#mb-title').value='My October title';doc.querySelector('#mb-subtitle').value='Edited subtitle';doc.querySelector('#mb-featured').checked=true;await doc.querySelector('#mb-details').onclick();assert.equal(payload.title,'My October title');assert.equal(payload.featured,true);assert.equal(payload.content,undefined);assert.equal(doc.querySelector('#mb-General').value,'Unsaved reading edits');assert.deepEqual(rows[0].published,content);assert.match(doc.querySelector('#mb-collections').textContent,/My October title/);}finally{d.window.close();}
});
