const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),{JSDOM}=require('jsdom');
const pause=()=>new Promise(r=>setTimeout(r,20));
test('Admin complimentary form saves terms, displays escaped recipient history and deactivates codes',async()=>{
 const dom=new JSDOM('<button data-tab="admin-promos">Promos</button><div data-complimentary-admin></div>',{runScripts:'outside-only',url:'https://lucehealing.com/'}),w=dom.window;w.adminPassword='admin-test';let codes=[],posted;
 w.fetch=async(url,opts)=>{if(opts.method==='POST'){posted=JSON.parse(opts.body);codes=[{...posted,id:1,active:true,max_redemptions:3,duration_days:30,redemption_count:1,redemptions:[{name:'<img src=x>',email:'reader@example.com',redeemed_at:'2026-09-24T12:00:00Z',access_until:null}]}];return {ok:true,json:async()=>codes[0]};}if(opts.method==='PATCH')codes[0].active=false;return {ok:true,json:async()=>codes};};
 w.eval(fs.readFileSync('complimentary-admin.js','utf8'));const f=w.document.querySelector('form');f.elements.code.value='READERS';f.elements.usage.value='multiple';f.elements.max_redemptions.value=3;f.elements.expiration.value='duration';f.dispatchEvent(new w.Event('change'));
 assert.equal(w.document.querySelector('[data-max]').hidden,false);assert.equal(w.document.querySelector('[data-days]').hidden,false);assert.equal(w.document.querySelector('[data-date]').hidden,true);
 f.dispatchEvent(new w.Event('submit',{cancelable:true}));await pause();assert.equal(posted.code,'READERS');assert.equal(posted.max_redemptions,'3');assert.equal(posted.expiration,'duration');assert.match(w.document.querySelector('[data-list]').textContent,/reader@example.com/);assert.equal(w.document.querySelectorAll('img').length,0);
 w.document.querySelector('[data-toggle]').click();await pause();assert.match(w.document.querySelector('[data-list]').textContent,/Deactivated/);dom.window.close();
});
test('Member signup submits complimentary code and displays access without payment controls',async()=>{
 const dom=new JSDOM('<div id="app"></div><p id="feedback"></p>',{runScripts:'outside-only',url:'https://lucehealing.com/members/account'}),w=dom.window;let member=null,signup;
 w.turnstile={render:()=>1,getResponse:()=> 'security-token'};
 w.fetch=async(url,opts)=>{let data,status=200;if(url.endsWith('/config'))data={private:false,purchasingEnabled:true,turnstileSiteKey:'site'};else if(url.endsWith('/signup')){signup=JSON.parse(opts.body);member={name:'Reader',email:'reader@example.com',membership_type:'complimentary',status:'complimentary',access:true,complimentary:true,access_until:null,verified:false,portal_available:false};data={success:true,message:'Your complimentary membership is ready.'};}else if(url.endsWith('/me')){data=member||{error:'Please sign in.'};if(!member)status=401;}else throw Error(url);return {ok:status===200,status,json:async()=>data};};
 w.eval(fs.readFileSync('private-membership/member.js','utf8'));await pause();w.document.getElementById('access-code').value='GIFT30';w.document.getElementById('access-code').dispatchEvent(new w.Event('input'));assert.match(w.document.querySelector('#signup button').textContent,/redeem/);
 w.document.getElementById('name').value='Reader';w.document.getElementById('email').value='reader@example.com';w.document.getElementById('new-password').value='test-password';w.document.getElementById('signup').dispatchEvent(new w.Event('submit',{cancelable:true}));await pause();
 assert.equal(signup.complimentary_code,'GIFT30');assert.equal(signup.turnstile_token,'security-token');assert.match(w.document.getElementById('app').textContent,/Complimentary Membership/);assert.match(w.document.getElementById('app').textContent,/Never expires/);assert.equal(w.document.getElementById('portal').hidden,true);assert.equal(w.document.querySelectorAll('[data-plan]').length,0);dom.window.close();
});
