const test=require('node:test'),assert=require('node:assert/strict'),fs=require('fs'),path=require('path');
const {JSDOM}=require('jsdom'),{render,install}=require('../public-navigation');
const files=['index.html','readings.html','about.html','sessions.html','pricing.html','blog.html','contact.html','faq.html','gift.html','private-membership/purchased.html','astrology-membership.html','reading.html','forecast.html','subscribe.html'];
test('all public destinations share one menu without replacing purchase navigation',()=>{
 for(const file of files){const html=render(fs.readFileSync(path.join(__dirname,'..',file),'utf8')),d=new JSDOM(html).window.document;assert.equal(d.querySelectorAll('.luce-site-header').length,1,file);assert.equal(d.querySelectorAll('.luce-site-header a.nav-link').length,13,file);for(const a of d.querySelectorAll('.luce-site-header a.nav-link'))assert(!a.getAttribute('href').includes('#'),file);assert.equal(render(html),html);if(file.includes('purchased'))assert(d.querySelector('#navigation'));if(file==='index.html'){assert(d.querySelector('#auth-nav-item'));assert(d.querySelector('#user-nav-item'));assert(!d.querySelector('#contact-form'));}if(file==='contact.html')assert(!d.querySelector('input[type=tel]'));}
});
test('shared control opens once despite old handlers; Escape and outside clicks close',()=>{
 const dom=new JSDOM(render(fs.readFileSync(path.join(__dirname,'../index.html'),'utf8')),{runScripts:'outside-only'}),w=dom.window,b=w.document.querySelector('.hamburger'),menu=w.document.querySelector('.nav-menu');
 b.addEventListener('click',()=>menu.classList.toggle('active'));w.eval(fs.readFileSync(path.join(__dirname,'../public-menu.js'),'utf8'));b.click();assert(menu.classList.contains('active'));assert.equal(b.getAttribute('aria-expanded'),'true');w.document.dispatchEvent(new w.KeyboardEvent('keydown',{key:'Escape'}));assert(!menu.classList.contains('active'));b.click();w.document.body.click();assert(!menu.classList.contains('active'));w.close();
});
test('HTML aliases and purchased routes use shared header; admin bypasses it',async()=>{
 const express=require('express'),app=express(),root=path.join(__dirname,'..');install(app,root);app.get('/personalized-monthly-reading',(q,r)=>r.sendFile(path.join(root,'private-membership/purchased.html')));app.get('/admin',(q,r)=>r.send('<body>Admin</body>'));const server=app.listen(0);try{for(const route of ['/sessions.html','/contact.html','/personalized-monthly-reading']){const r=await fetch(`http://127.0.0.1:${server.address().port}${route}`);assert.equal(r.status,200);assert((await r.text()).includes('luce-site-header'));}const admin=await fetch(`http://127.0.0.1:${server.address().port}/admin`);assert(!(await admin.text()).includes('luce-site-header'));}finally{server.close();}
});
