(()=>{
const roots=[...document.querySelectorAll('[data-complimentary-admin]')];if(!roots.length)return;
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const pw=()=>typeof adminPassword!=='undefined'?adminPassword:typeof adminPw!=='undefined'?adminPw:'';
const api=async(p='',method='GET',body)=>{const r=await fetch('/api/admin/membership/complimentary-codes'+p+'?password='+encodeURIComponent(pw()),{method,headers:{'Content-Type':'application/json'},body:body?JSON.stringify(body):undefined});const x=await r.json();if(!r.ok)throw Error(x.error||'Unable to load codes.');return x;};
const date=x=>x?new Date(x).toLocaleString('en-US',{timeZone:'America/Los_Angeles',dateStyle:'medium',timeStyle:'short'})+' Pacific':'Never expires';
for(const [i,root] of roots.entries()){
root.classList.add('luce-newsletter-admin');const id='comp-'+i+'-';
root.innerHTML=`<section class="nl-card"><h3>Complimentary Membership codes</h3><p>Give full Astrology Membership access for $0. No credit card, Stripe checkout, automatic renewal or charge. Share the code and <a href="/members/account">member sign-in link</a>.</p><form><label for="${id}code">Access code</label><input id="${id}code" name="code" required minlength="3" maxlength="64" pattern="[A-Za-z0-9_-]{3,64}" placeholder="e.g. WELCOME-CHRISTINA" autocapitalize="characters"><label for="${id}name">Name / label (optional)</label><input id="${id}name" name="name" maxlength="120"><label for="${id}usage">Allowed uses</label><select id="${id}usage" name="usage"><option value="once">Single use — one recipient</option><option value="multiple">Multiple recipients</option></select><div data-max hidden><label for="${id}max">Maximum redemptions (leave blank for unlimited)</label><input id="${id}max" name="max_redemptions" type="number" min="1" max="1000000" step="1"></div><label for="${id}expiration">Complimentary membership expires</label><select id="${id}expiration" name="expiration"><option value="never">Never</option><option value="duration">After a duration from redemption</option><option value="date">On a specific date and time</option></select><div data-days hidden><label for="${id}days">Number of days from redemption</label><input id="${id}days" name="duration_days" type="number" min="1" max="36500" step="1" value="30"></div><div data-date hidden><label for="${id}date">Access ends — Pacific time (for every recipient)</label><input id="${id}date" name="localTime" type="datetime-local"><label for="${id}occurrence">If the clock time occurs twice</label><select id="${id}occurrence" name="occurrence"><option value="unknown">Ask me if ambiguous</option><option value="earlier">First occurrence</option><option value="later">Second occurrence</option></select></div><p class="nl-muted">Expiration ends access only. Recipients can choose to buy membership afterward. Deactivating a code blocks new redemptions; it does not remove access already granted. Create a new code for different terms.</p><button type="submit">Create complimentary code</button></form><p data-message role="status" aria-live="polite"></p><button type="button" data-refresh>Refresh complimentary codes</button><div data-list></div></section>`;
const form=root.querySelector('form'),msg=root.querySelector('[data-message]');
const fields=()=>{root.querySelector('[data-max]').hidden=form.elements.usage.value!=='multiple';root.querySelector('[data-days]').hidden=form.elements.expiration.value!=='duration';root.querySelector('[data-date]').hidden=form.elements.expiration.value!=='date';form.elements.localTime.required=form.elements.expiration.value==='date';};form.onchange=fields;
async function refresh(){const codes=await api();root.querySelector('[data-list]').innerHTML=codes.map(c=>`<article class="nl-row"><h4>${esc(c.code)}</h4><p>${esc(c.name)} · ${c.active?'Active':'Deactivated'} · ${c.redemption_count}/${c.max_redemptions??'Unlimited'} redemptions</p><p>Access: ${c.duration_days?c.duration_days+' days from redemption':esc(date(c.expires_at))}</p><button type="button" data-toggle="${c.id}" data-active="${!c.active}">${c.active?'Deactivate — block new redemptions':'Reactivate code'}</button><details><summary>Who redeemed this code (${c.redemption_count})</summary>${c.redemptions.map(r=>`<p><strong>${esc(r.name)}</strong> · ${esc(r.email)}<br>Redeemed: ${esc(date(r.redeemed_at))}<br>Access: ${esc(date(r.access_until))}</p>`).join('')||'<p>No redemptions yet.</p>'}</details></article>`).join('')||'<p>No complimentary codes yet.</p>';}
const run=fn=>async e=>{e?.preventDefault();const b=e?.target?.closest?.('button')||form.querySelector('button');b.disabled=true;msg.textContent='';try{await fn(e);}catch(err){msg.textContent=err.message;}finally{b.disabled=false;}};
form.onsubmit=run(async()=>{const c=await api('','POST',Object.fromEntries(new FormData(form)));form.reset();fields();await refresh();msg.textContent='Created '+c.code+'. Share it with your recipient. No emails were sent.';});
root.querySelector('[data-refresh]').onclick=run(refresh);
root.addEventListener('click',e=>{const b=e.target.closest('[data-toggle]');if(!b)return;run(async()=>{await api('/'+b.dataset.toggle,'PATCH',{active:b.dataset.active==='true'});await refresh();msg.textContent='Code updated. Previously granted memberships are unchanged.';})(e);});
document.querySelector('[data-tab="admin-promos"]')?.addEventListener('click',run(refresh));
const previous=window.loadComplimentaryAdmin;window.loadComplimentaryAdmin=async()=>{await previous?.();await refresh().catch(e=>msg.textContent=e.message);};
}
})();
