const catalog=window.luceGiftCatalog;
const byId=id=>document.getElementById(id);
const productSelect=byId('gift-product');
for(const p of catalog){const option=document.createElement('option');option.value=p.id;option.textContent=p.name+' — $'+p.price;productSelect.append(option);}
function describe(p){return p.name+' · $'+p.price+'. Written delivery: '+p.days+' after the recipient supplies their details.'+(p.consultation?' Includes a '+p.consultation+'-minute consultation, arranged with the recipient.':' No consultation included.');}
function updateGift(){const p=catalog.find(p=>p.id===productSelect.value);byId('gift-description').textContent=describe(p);byId('gift-buy').textContent='Buy Gift — $'+p.price;}
productSelect.addEventListener('change',updateGift);updateGift();
async function api(path,body){const response=await fetch(path,body?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}:{});const data=await response.json();if(!response.ok)throw new Error(data.error||'Please try again.');return data;}
byId('gift-purchase').addEventListener('submit',async e=>{e.preventDefault();if(!e.target.reportValidity())return;const button=byId('gift-buy');button.disabled=true;try{const data=await api('/api/gifts/checkout',Object.fromEntries(new FormData(e.target)));if(!data.url)throw new Error('Unable to open checkout. Please try again.');location.href=data.url;}catch(err){byId('purchase-status').textContent=err.message;}finally{button.disabled=false;}});
const token=new URLSearchParams(location.search).get('token');let redeemedProduct;
if(token){byId('purchase').hidden=true;document.querySelector('header').hidden=true;byId('redemption').hidden=false;byId('gift-redeem').hidden=true;api('/api/gifts/redeem?token='+encodeURIComponent(token)).then(gift=>{redeemedProduct=catalog.find(p=>p.id===gift.product);byId('redeem-title').textContent='Your gift: '+redeemedProduct.name;byId('redeem-description').textContent=describe(redeemedProduct);byId('gift-note').textContent=gift.message?'A message for you: '+gift.message:'';byId('gift-redeem').hidden=false;byId('question-fields').hidden=!redeemedProduct.question;byId('recipient-question').required=!!redeemedProduct.question;byId('recipient-birth-time').required=!redeemedProduct.question;byId('birth-time-label').textContent=redeemedProduct.question?'Birth time (optional)':'Birth time *';byId('consultation-fields').hidden=!redeemedProduct.consultation;for(const id of ['consultation-format','recipient-timezone','recipient-availability'])byId(id).required=!!redeemedProduct.consultation;byId('recipient-birth-date').max=new Date().toISOString().slice(0,10);}).catch(err=>{byId('redeem-status').textContent=err.message;byId('redemption').append(byId('redeem-status'));});}
byId('consultation-format').addEventListener('change',()=>byId('recipient-phone').required=byId('consultation-format').value==='phone');
byId('gift-redeem').addEventListener('submit',async e=>{e.preventDefault();if(!e.target.reportValidity())return;const button=e.target.querySelector('button');button.disabled=true;try{await api('/api/gifts/redeem',{token,...Object.fromEntries(new FormData(e.target))});byId('redemption').hidden=true;byId('redeemed').hidden=false;byId('redeemed-next').textContent=redeemedProduct.consultation?'Your order includes your consultation preferences for Christina to follow up.':'Your order includes the details needed for your written reading.';}catch(err){byId('redeem-status').textContent=err.message;}finally{button.disabled=false;}});

const purchaseSession=new URLSearchParams(location.search).get('session_id');
if(purchaseSession){byId('purchase').hidden=true;byId('gift-ready').hidden=false;api('/api/gifts/purchase?session_id='+encodeURIComponent(purchaseSession)).then(data=>{byId('gift-ready-description').textContent=describe(catalog.find(p=>p.id===data.product));const link=location.origin+'/gift?token='+encodeURIComponent(data.token);byId('redeem-link').href=link;byId('redeem-link').textContent=link;}).catch(err=>byId('gift-ready-description').textContent=err.message);}
