(()=>{const root=document.querySelector('[data-membership-admin]');if(!root)return;root.classList.add('luce-newsletter-admin');
const signs=['Aries','Taurus','Gemini','Cancer','Leo','Virgo','Libra','Scorpio','Sagittarius','Capricorn','Aquarius','Pisces'];
const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const pw=()=>typeof adminPassword!=='undefined'?adminPassword:typeof adminPw!=='undefined'?adminPw:'';
const api=async(p,m='GET',b)=>{const r=await fetch('/api/admin/membership/'+p+'?password='+encodeURIComponent(pw()),{method:m,cache:'no-store',headers:{'Content-Type':'application/json'},body:b?JSON.stringify(b):undefined});const x=await r.json();if(!r.ok)throw Error(x.error);return x;};
const pacific=x=>new Date(x).toLocaleString('en-US',{timeZone:'America/Los_Angeles',month:'long',day:'numeric',year:'numeric',hour:'numeric',minute:'2-digit',timeZoneName:'short'});
const localPacific=x=>{const parts=new Intl.DateTimeFormat('en-CA',{timeZone:'America/Los_Angeles',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).formatToParts(new Date(x));const get=t=>parts.find(p=>p.type===t).value;return get('year')+'-'+get('month')+'-'+get('day')+'T'+get('hour')+':'+get('minute');};
const monthName=m=>new Date(m+'-15T12:00:00Z').toLocaleDateString('en-US',{month:'long',year:'numeric'});
const displayTitle=r=>!r?.title||/^(Current month|Demonstration month|Monthly Horoscopes \(\d{4}-\d{2}\))$/i.test(r.title)?monthName(r?.display_month||r?.month||localPacific(new Date()).slice(0,7))+' Horoscopes':r.title;
const status=r=>r?.scheduled_at?'scheduled':r?.published&&!r.collection_hidden?'published':'draft';
let months=[],selected=null,busy=false,draftId=null,baseline='',dirty=false;const el=id=>document.getElementById('mb-'+id);
root.innerHTML=`<style>
[data-membership-admin] [hidden]{display:none!important}
[data-membership-admin] input,[data-membership-admin] textarea,[data-membership-admin] select{box-sizing:border-box;max-width:100%;font-size:16px}
[data-membership-admin] button,[data-membership-admin] summary{min-height:44px}
[data-membership-admin] .mb-heading{overflow-wrap:anywhere}
[data-membership-admin] #mb-action-message:not(:empty){padding:14px;background:#eee5f5;border-radius:8px}
[data-membership-admin] #mb-primary{display:flex;flex-wrap:wrap;gap:8px;margin-top:20px}
[data-membership-admin] #mb-primary button{flex:1;min-width:90px}
[data-membership-admin] #mb-editor input:not([type="checkbox"]),[data-membership-admin] #mb-editor select,[data-membership-admin] #mb-editor textarea{width:100%}
[data-membership-admin] #mb-editor label{display:block;margin-top:16px}
[data-membership-admin] #mb-general-section{margin-top:20px}
[data-membership-admin] #mb-new,[data-membership-admin] #mb-publish,[data-membership-admin] #mb-schedule{background:#694579;color:#fff}
[data-membership-admin] #mb-scheduling{margin-top:18px}
</style><section class="nl-card"><div id="mb-list"><h3>Members Only Posts</h3><button id="mb-new">+ Create New Post</button><p id="mb-message" role="status" aria-live="polite"></p><div id="mb-recovery"></div><div id="mb-collections"></div></div>
<div id="mb-editor" hidden><button id="mb-back">← All posts</button><h3 id="mb-heading" class="mb-heading" tabindex="-1"></h3><p id="mb-editor-status" class="nl-muted"></p>
<label for="mb-title">Post title</label><input id="mb-title" maxlength="180">
<label for="mb-kind">Post type</label><select id="mb-kind"><option value="special">Special Astrology Guidance</option><option value="monthly">Monthly Horoscopes</option></select>
<label for="mb-month">Month and year</label><input id="mb-month" type="month">
<details id="mb-general-section" open><summary>General Guidance</summary><label for="mb-General">General Guidance</label><textarea id="mb-General" rows="7" maxlength="20000"></textarea></details>
<p id="mb-completeness" role="status"></p>${signs.map(s=>`<details><summary>${s}</summary><label for="mb-${s}">${s} guidance</label><textarea id="mb-${s}" rows="7" maxlength="20000"></textarea></details>`).join('')}
<details id="mb-more"><summary>More options</summary><label for="mb-subtitle">Short description (optional)</label><textarea id="mb-subtitle" rows="2" maxlength="500"></textarea><button id="mb-preview">Preview draft</button><label class="nl-check"><input type="checkbox" id="mb-featured">Featured monthly horoscopes</label><label class="nl-check"><input type="checkbox" id="mb-demo">Internal test guidance (excluded from paying members)</label><details><summary>Display settings for saved guidance</summary><label for="mb-status">Display status</label><select id="mb-status"><option value="draft">Draft</option><option value="published">Published</option><option value="scheduled">Scheduled</option></select><p class="nl-muted">Applies display settings only; does not save reading edits. Publication date uses the Pacific Time field under Schedule publication.</p><button id="mb-details">Apply display settings only</button></details><button id="mb-unpublish">Unpublish</button><button id="mb-delete" disabled>Delete post</button></details>
<div id="mb-draft-preview" hidden></div><p class="nl-muted">Saved edits stay in draft until published. A previously published version stays visible. No emails are sent.</p><div id="mb-primary"><button id="mb-save">Save Draft</button><button id="mb-publish">Publish Now</button><button id="mb-open-schedule">Schedule</button></div><div id="mb-scheduling" hidden><label for="mb-publish-time">Publish date and time — Pacific Time</label><input id="mb-publish-time" type="datetime-local"><details><summary>Daylight saving time options</summary><label for="mb-publish-occurrence">If this time occurs twice when clocks go back</label><select id="mb-publish-occurrence"><option value="unknown">Ask me if needed</option><option value="earlier">First occurrence (PDT)</option><option value="later">Second occurrence (PST)</option></select></details><p class="nl-muted">All sections publish together. Save Draft cancels a pending schedule.</p><button id="mb-schedule">Save &amp; Schedule</button><button id="mb-cancel-schedule">Cancel schedule</button><p id="mb-schedule-status" role="status"></p></div><p id="mb-action-message" role="status" aria-live="assertive"></p></div></section>
<details class="nl-card" id="mb-accounts"><summary>Member accounts</summary><p class="nl-muted">Private accounts are separate from newsletter subscriptions and existing customer records.</p><div id="mb-members"></div></details><details class="nl-card" id="mb-membership-settings"><summary>Membership settings</summary><p class="nl-status" id="mb-launch-status">Loading membership status…</p><div class="nl-actions"><button id="mb-refresh">Refresh membership</button><a href="/members/review" target="_blank" rel="noopener">Open private member preview</a></div><p id="mb-config" class="nl-muted"></p></details>
`;
function showEditor(show){el('list').hidden=show;el('editor').hidden=!show;el('accounts').hidden=show;el('membership-settings').hidden=show;if(show){el('heading').textContent=selected?'Editing: '+displayTitle(selected):'Create New Post';el('heading').focus();}}
const confirmed=action=>'✓ '+action+' successfully at '+new Date().toLocaleTimeString('en-US',{timeZone:'America/Los_Angeles',hour:'numeric',minute:'2-digit'})+' Pacific Time';

function message(text){el('message').textContent=text;el('action-message').textContent=text;}
const run=fn=>async()=>{if(busy)return;busy=true;const controls=[...root.querySelectorAll('input,textarea,select,button')].map(x=>[x,x.disabled]);controls.forEach(([x])=>x.disabled=true);message('Working…');try{await fn();}catch(e){checkpoint();message('Not completed: '+e.message+' Your editor text has been kept.');}finally{if(el('action-message').textContent==='Working…')message(el('message').textContent==='Working…'?'':el('message').textContent);busy=false;controls.forEach(([x,disabled])=>x.disabled=disabled);el('details').disabled=!selected;el('delete').disabled=!selected;el('featured').disabled=el('kind').value==='special';el('cancel-schedule').disabled=!selected?.scheduled_at;completeness();}};
const recoveryPrefix='luce-guidance-recovery-v1:';
function capture(){return {id:draftId,revision:selected?.revision,details:detailValues(),demo:el('demo').checked,content:Object.fromEntries(['General',...signs].map(s=>[s,el(s).value]))};}
function checkpoint(){if(!draftId)return;const data=capture();dirty=JSON.stringify(data)!==baseline;if(!dirty)return;try{localStorage.setItem(recoveryPrefix+draftId,JSON.stringify({...data,savedAt:new Date().toISOString()}));el('editor-status').textContent='Unsaved changes — recovery copy kept on this browser. Use Save draft to store on Luce Healing.';}catch(_){el('editor-status').textContent='Unsaved changes — browser recovery unavailable. Keep this page open until Save draft succeeds.';}}
function recoveries(){const rows=[];try{for(let i=0;i<localStorage.length;i++){const key=localStorage.key(i);if(key.startsWith(recoveryPrefix)){try{rows.push(JSON.parse(localStorage.getItem(key)));}catch(_){}}}}catch(_){}return rows;}
function recoveryOptions(){el('recovery').innerHTML=recoveries().map(r=>`<p>Recovery copy: ${esc(r.details.title||'Untitled collection')} · ${esc(pacific(r.savedAt))} <button data-recover="${esc(r.id)}">Recover draft</button></p>`).join('');}
function clearRecovery(){try{localStorage.removeItem(recoveryPrefix+draftId);}catch(_){}recoveryOptions();}
function switchForm(row){if(busy)return false;checkpoint();if(dirty&&!confirm('Leave these unsaved edits? A recovery copy is kept in this browser when available.'))return false;form(row);message('');showEditor(true);return true;}
root.addEventListener('input',checkpoint);root.addEventListener('change',checkpoint);
window.addEventListener('beforeunload',e=>{checkpoint();if(dirty){e.preventDefault();e.returnValue='';}});
document.addEventListener('visibilitychange',()=>{if(document.hidden)checkpoint();});
root.addEventListener('click',e=>{const b=e.target.closest('[data-recover]');if(!b||busy)return;const r=recoveries().find(x=>x.id===b.dataset.recover);if(!r)return;if(!switchForm(null))return;draftId=r.id;selected=r.revision==null?null:{month:r.id,revision:r.revision};el('kind').value=r.details.collection_type;el('title').value=r.details.title;el('month').value=r.details.display_month;el('subtitle').value=r.details.subtitle;el('featured').checked=r.details.featured;el('status').value=r.details.status;el('publish-time').value=r.details.localTime;el('publish-occurrence').value=r.details.occurrence;el('demo').checked=r.demo;['General',...signs].forEach(k=>el(k).value=r.content[k]||'');el('heading').textContent='Recovered draft: '+(r.details.title||'Untitled guidance');el('featured').disabled=el('kind').value==='special';checkpoint();completeness();message('Recovered browser draft. Review and Save draft to store it on Luce Healing.');});
function form(row){selected=row||null;draftId=row?.month||'collection-'+crypto.randomUUID();el('kind').value=row?.collection_type||'special';el('featured').disabled=el('kind').value==='special';el('month').value=row?.display_month||(/^\d{4}-\d{2}$/.test(row?.month||'')?row.month:'');el('month').disabled=false;el('title').value=row?displayTitle(row):'';el('subtitle').value=row?.subtitle||'';el('status').value=status(row);el('publish-time').value=row?.scheduled_at?localPacific(row.scheduled_at):row?.published_at?localPacific(row.published_at):'';el('publish-occurrence').value='unknown';el('featured').checked=!!row?.featured_at;el('details').disabled=!row;el('delete').disabled=!row;el('demo').checked=!!row?.demo;['General',...signs].forEach(s=>el(s).value=row?.draft?.[s]||'');el('draft-preview').hidden=true;el('editor-status').textContent=row?.scheduled_at?'Scheduled — '+pacific(row.scheduled_at):row?(row.published&&!row.collection_hidden?'Published '+pacific(row.published_at)+'. Saved edits remain draft.':'Draft — not visible to members.'):'New draft';el('scheduling').hidden=true;el('general-section').open=true;el('more').open=false;el('schedule-status').textContent=row?.scheduled_at?'Scheduled: '+pacific(row.scheduled_at)+' — Pacific time. The general reading (if entered) and all 12 signs publish together.':'No publication scheduled.';el('cancel-schedule').disabled=!row?.scheduled_at;completeness();baseline=JSON.stringify(capture());dirty=false;recoveryOptions();el('heading').textContent=row?'Editing: '+displayTitle(row):'Create New Post';}
function completeness(){const missing=signs.filter(s=>!el(s).value.trim());el('completeness').textContent=(12-missing.length)+'/12 signs complete. '+(missing.length?'Missing: '+missing.join(', '):'Ready to publish or schedule.');el('schedule').disabled=!!missing.length;el('publish').disabled=!!missing.length;}
signs.forEach(s=>el(s).addEventListener('input',completeness));
function monthOptions(){
 el('collections').innerHTML=[...months].sort((a,b)=>new Date(b.published_at||b.updated_at||0)-new Date(a.published_at||a.updated_at||0)).map(x=>`<article class="nl-row"><strong>${esc(displayTitle(x))}</strong><p>${x.collection_type==='special'?'Special Astrology Guidance':esc(monthName(x.display_month||x.month))} · ${status(x).replace(/^./,c=>c.toUpperCase())}${x.featured_at?' · Featured':''}${x.demo?' · Internal test':''}</p><p>Publish date: ${x.scheduled_at?esc(pacific(x.scheduled_at)):x.published_at?esc(pacific(x.published_at)):'Not published'}</p><button data-open-month="${x.month}">Edit</button></article>`).join('')||'<p>No saved posts yet.</p>';
}
async function refresh(){const [config,list,members]=await Promise.all([api('status'),api('horoscopes'),api('members')]);el('launch-status').textContent=config.purchasingEnabled?'Public membership signup and subscriptions are live.':'Public purchasing is disabled. Private review is available.';months=list;if(selected){const fresh=months.find(x=>x.month===selected.month);if(fresh&&fresh.revision!==selected.revision){el('message').textContent='This post has changed. Open it again from All posts before editing.';}}monthOptions();el('config').textContent='Test inbox: '+config.testEmail+'. Stripe sandbox: '+(config.sandboxConfigured?'connected':'not configured')+'. Portal: '+(config.portalConfigured?'configured':'not configured')+'.';el('members').innerHTML=members.map(m=>`<article class="nl-row"><strong>${esc(m.email)}</strong><p>${esc(m.name)} · ${m.membership_type?.startsWith('complimentary')?'Complimentary Membership · ':''}${esc(m.tier)} · ${esc(m.status)}</p><p class="nl-muted">Email confirmed: ${m.verified?'Yes':'No'}<br>Access through: ${m.complimentary&&!m.access_until?'Never expires':m.access_until?new Date(m.access_until).toLocaleString():'None'}<br>Billing period ends: ${m.billing_period_end?new Date(m.billing_period_end).toLocaleString():'No paid subscription'}<br>Cancellation scheduled: ${m.cancel_at_period_end?'Yes':'No'}<br>Created: ${new Date(m.created_at).toLocaleString()}</p>${m.is_test?`<label for="mb-state-${m.id}">Private preview state</label><select id="mb-state-${m.id}"><option value="preview">Preview active (7 days)</option><option value="past_due">Payment problem — no access</option><option value="expired">Expired — no access</option><option value="canceled">Canceled — no access</option></select><button data-member-state="${m.id}">Apply preview state</button>`:''}</article>`).join('')||'<p>No membership accounts yet. Create your test account in the private preview.</p>';}
function detailValues(){return {collection_type:el('kind').value,title:el('title').value,display_month:el('month').value,subtitle:el('subtitle').value,featured:el('featured').checked,status:el('status').value,localTime:el('publish-time').value,occurrence:el('publish-occurrence').value};}
async function readBack(expected,published=false){const row=await api('collections/'+expected.month);const keys=['title','subtitle','display_month','collection_type','demo'];if(row.revision!==expected.revision||keys.some(k=>row[k]!==expected[k])||['General',...signs].some(k=>row.draft[k]!==expected.draft[k])||!!row.featured_at!==!!expected.featured_at||(published&&(row.collection_hidden||row.published_title!==expected.title||row.published_demo!==expected.demo||['General',...signs].some(k=>row.published?.[k]!==expected.draft[k]))))throw Error('The stored copy could not be verified. Keep your recovery draft and retry.');return row;}
async function save(){checkpoint();const data=capture();const saved=await api('collections/'+draftId,'PUT',{...data.details,content:data.content,demo:data.demo,revision:selected?.revision});
 // Preserve the ID/revision even if the independent read-back fails.
 selected=saved;const row=await readBack(saved);if(['General',...signs].some(k=>row.draft[k]!==data.content[k])||row.title!==data.details.title.trim()||row.subtitle!==data.details.subtitle||row.display_month!==data.details.display_month||row.collection_type!==data.details.collection_type||row.demo!==data.demo)throw Error('The stored draft differs from your editor. Your recovery copy is retained.');form(row);clearRecovery();months=months.filter(x=>x.month!==row.month).concat(row);monthOptions();}
el('kind').onchange=()=>{el('featured').disabled=el('kind').value==='special';if(el('featured').disabled)el('featured').checked=false;};
el('status').onchange=()=>{const current=localPacific(new Date());if(el('status').value==='published'&&(!el('publish-time').value||el('publish-time').value>current))el('publish-time').value=current;if(el('status').value==='scheduled'&&el('publish-time').value<=current)el('publish-time').value='';};
el('details').onclick=run(async()=>{if(!selected)return;checkpoint();const values=detailValues(),unsaved=Object.fromEntries(['General',...signs].map(k=>[k,el(k).value]));selected=await api('horoscopes/'+selected.month+'/details','PATCH',{...values,revision:selected.revision});form(selected);for(const [key,value] of Object.entries(unsaved))el(key).value=value;checkpoint();completeness();await refresh();message('Display settings applied. Reading edits are still unsaved; use Save draft below.');});
root.addEventListener('click',e=>{const b=e.target.closest('[data-open-month]');if(!b||busy)return;if(!switchForm(months.find(x=>x.month===b.dataset.openMonth)))return;monthOptions();el('title').scrollIntoView({behavior:'smooth',block:'center'});});
el('save').onclick=run(async()=>{await save();message(confirmed('Saved'));});el('refresh').onclick=run(refresh);
el('open-schedule').onclick=()=>{el('scheduling').hidden=false;el('publish-time').focus();};
el('new').onclick=()=>{switchForm(null);};el('back').onclick=()=>{checkpoint();if(dirty&&!confirm('Leave unsaved edits? A recovery copy is kept on this browser when available.'))return;form();showEditor(false);message('');};
el('delete').onclick=run(async()=>{if(!selected||!confirm('Delete this collection from the editor and members area?'))return;await api('collections/'+selected.month,'DELETE',{revision:selected.revision,title:selected.title});const rows=await api('horoscopes');if(rows.some(x=>x.month===selected.month))throw Error('Deletion could not be verified.');clearRecovery();months=rows;form();showEditor(false);monthOptions();message('Collection deleted.');});
el('preview').onclick=()=>{el('draft-preview').hidden=false;el('draft-preview').innerHTML=`<h3>${esc(el('title').value)} — draft preview</h3>${el('demo').checked?'<p class="nl-status">DEMONSTRATION CONTENT — not an actual forecast</p>':''}<p>The general reading comes first. Tap a heading to open or close its reading.</p>${['General',...signs].map(s=>`<details style="border-bottom:1px solid #e5dcec;padding:8px 0"><summary style="padding:12px 0;cursor:pointer;font-weight:600;color:#624373">${s==='General'?'General monthly reading — all signs':s}</summary><p style="white-space:pre-wrap">${esc(el(s).value||(s==='General'?'No general reading entered. This optional section is hidden from members until you add and publish it.':'No draft text entered for this sign.'))}</p></details>`).join('')}`;el('draft-preview').scrollIntoView({behavior:'smooth',block:'start'});};
el('publish').onclick=run(async()=>{if(!confirm('Save and publish this guidance to the members area? No emails will be sent.'))return;await save();const published=await api('horoscopes/'+selected.month+'/publish','POST',{revision:selected.revision});selected=published;form(await readBack(published,true));clearRecovery();await refresh();message(confirmed('Published'));});
el('schedule').onclick=run(async()=>{const localTime=el('publish-time').value,occurrence=el('publish-occurrence').value;if(!localTime)throw Error('Choose the publication date and time in Pacific time.');if(!confirm('Save and schedule the general reading (if entered) and all 12 signs at '+localTime.replace('T',' ')+' Pacific time? No emails will be sent.'))return;await save();selected=await api('horoscopes/'+selected.month+'/schedule','POST',{revision:selected.revision,localTime,occurrence});const verified=await readBack(selected);if(!verified.scheduled_at||verified.scheduled_at!==selected.scheduled_at)throw Error('The schedule could not be verified.');form(verified);await refresh();message(confirmed('Scheduled')+' — publishes '+pacific(selected.scheduled_at));});
el('cancel-schedule').onclick=run(async()=>{if(!selected?.scheduled_at)return;selected=await api('horoscopes/'+selected.month+'/cancel-schedule','POST',{revision:selected.revision});form(selected);await refresh();el('message').textContent='Schedule canceled; content retained as draft. Any previously published edition is unchanged. No emails sent.';});
el('unpublish').onclick=run(async()=>{if(!selected||!confirm('Hide this month from members while retaining the draft?'))return;selected=await api('horoscopes/'+selected.month+'/unpublish','POST',{revision:selected.revision});form(selected);await refresh();el('message').textContent='Month unpublished; draft retained.';});
root.addEventListener('click',e=>{const b=e.target.closest('[data-member-state]');if(!b)return;run(async()=>{await api('members/'+b.dataset.memberState+'/preview','POST',{status:el('state-'+b.dataset.memberState).value});await refresh();el('message').textContent='Preview state updated. No payment or email occurred.';})();});
window.loadMembershipAdmin=run(refresh);document.querySelector('[data-tab="admin-membership"]')?.addEventListener('click',window.loadMembershipAdmin);form();
})();


