(()=>{const root=document.querySelector('[data-membership-admin]');if(!root)return;root.classList.add('luce-newsletter-admin');
const signs=['Aries','Taurus','Gemini','Cancer','Leo','Virgo','Libra','Scorpio','Sagittarius','Capricorn','Aquarius','Pisces'];
const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const pw=()=>typeof adminPassword!=='undefined'?adminPassword:typeof adminPw!=='undefined'?adminPw:'';
const api=async(p,m='GET',b)=>{const r=await fetch('/api/admin/membership/'+p+'?password='+encodeURIComponent(pw()),{method:m,headers:{'Content-Type':'application/json'},body:b?JSON.stringify(b):undefined});const x=await r.json();if(!r.ok)throw Error(x.error);return x;};
let months=[],selected=null,busy=false;const el=id=>document.getElementById('mb-'+id);
root.innerHTML=`<section class="nl-card"><h3>Membership — private review</h3><p class="nl-status">Public purchasing is disabled. There are no live recurring charges. Both tiers and prices await confirmation.</p><div class="nl-actions"><button id="mb-refresh">Refresh membership</button><a href="/members/review" target="_blank" rel="noopener">Open private member preview</a></div><p id="mb-config" class="nl-muted"></p><p id="mb-message" role="status" aria-live="polite"></p></section><section class="nl-card"><h3>Monthly horoscopes</h3><label for="mb-existing">Saved months</label><select id="mb-existing"><option value="">New month</option></select><label for="mb-month">Month</label><input id="mb-month" type="month"><label for="mb-title">Title</label><input id="mb-title" maxlength="180"><label class="nl-check"><input type="checkbox" id="mb-demo">Demonstration content (clearly labeled to members)</label><p class="nl-muted">Members can read all 12 signs. Saving keeps changes in draft; the previous published version stays visible until you publish again. Publishing here never emails subscribers.</p>${signs.map(s=>`<details><summary style="padding:12px 0;cursor:pointer">${s}</summary><label for="mb-${s}">${s} horoscope</label><textarea id="mb-${s}" rows="7" maxlength="20000"></textarea></details>`).join('')}<div class="nl-actions"><button id="mb-save">Save draft</button><button id="mb-preview">Preview draft</button><button id="mb-publish">Publish privately</button><button id="mb-unpublish">Unpublish</button><button id="mb-new">New month</button></div><p id="mb-editor-status" class="nl-muted"></p><div id="mb-draft-preview" hidden></div></section><section class="nl-card"><h3>Member accounts</h3><p class="nl-muted">Private accounts are separate from newsletter subscriptions and existing customer records. Preview-state controls do not charge cards or send emails.</p><div id="mb-members"></div></section>`;
const run=fn=>async()=>{if(busy)return;busy=true;el('message').textContent='';try{await fn();}catch(e){el('message').textContent=e.message;}finally{busy=false;}};
function form(row){selected=row||null;el('month').value=row?.month||new Date().toISOString().slice(0,7);el('month').disabled=!!row;el('title').value=row?.title||'';el('demo').checked=!!row?.demo;signs.forEach(s=>el(s).value=row?.draft?.[s]||'');el('draft-preview').hidden=true;el('editor-status').textContent=row?(row.published_at?'Published privately '+new Date(row.published_at).toLocaleString()+'. Saved edits remain draft.':'Draft — not visible to members.'):'New draft';}
function monthOptions(){el('existing').innerHTML='<option value="">New month</option>'+months.map(x=>`<option value="${x.month}">${esc(x.title)} (${x.month})${x.demo?' — demonstration':''}</option>`).join('');el('existing').value=selected?.month||'';}
async function refresh(){const [config,list,members]=await Promise.all([api('status'),api('horoscopes'),api('members')]);months=list;monthOptions();el('config').textContent='Test inbox: '+config.testEmail+'. Stripe sandbox: '+(config.sandboxConfigured?'connected':'not configured')+'. Portal: '+(config.portalConfigured?'configured':'not configured')+'.';el('members').innerHTML=members.map(m=>`<article class="nl-row"><strong>${esc(m.email)}</strong><p>${esc(m.name)} · ${esc(m.tier)} · ${esc(m.status)}</p><p class="nl-muted">Email confirmed: ${m.verified?'Yes':'No'}<br>Access through: ${m.access_until?new Date(m.access_until).toLocaleString():'None'}<br>Billing period ends: ${m.billing_period_end?new Date(m.billing_period_end).toLocaleString():'No paid subscription'}<br>Cancellation scheduled: ${m.cancel_at_period_end?'Yes':'No'}<br>Created: ${new Date(m.created_at).toLocaleString()}</p><label for="mb-state-${m.id}">Private preview state</label><select id="mb-state-${m.id}"><option value="preview">Preview active (7 days)</option><option value="past_due">Payment problem — no access</option><option value="expired">Expired — no access</option><option value="canceled">Canceled — no access</option></select><button data-member-state="${m.id}">Apply preview state</button></article>`).join('')||'<p>No membership accounts yet. Create your test account in the private preview.</p>';}
async function save(){const content=Object.fromEntries(signs.map(s=>[s,el(s).value]));selected=await api('horoscopes/'+el('month').value,'PUT',{title:el('title').value,content,demo:el('demo').checked,revision:selected?.revision});form(selected);await refresh();}
el('save').onclick=run(async()=>{await save();el('message').textContent='Draft saved. No emails sent.';});el('refresh').onclick=run(refresh);
el('existing').onchange=()=>form(months.find(x=>x.month===el('existing').value));el('new').onclick=()=>{form();el('existing').value='';};
el('preview').onclick=()=>{el('draft-preview').hidden=false;el('draft-preview').innerHTML=`<h3>${esc(el('title').value)} — draft preview</h3>${el('demo').checked?'<p class="nl-status">DEMONSTRATION CONTENT — not an actual forecast</p>':''}${signs.map(s=>`<h4>${s}</h4><p style="white-space:pre-wrap">${esc(el(s).value)}</p>`).join('')}`;el('draft-preview').scrollIntoView({behavior:'smooth',block:'start'});};
el('publish').onclick=run(async()=>{if(!confirm('Save and publish this month to the private members area? No emails will be sent.'))return;await save();selected=await api('horoscopes/'+selected.month+'/publish','POST',{revision:selected.revision});form(selected);await refresh();el('message').textContent='Published to the private members area. No emails sent.';});
el('unpublish').onclick=run(async()=>{if(!selected||!confirm('Hide this month from members while retaining the draft?'))return;selected=await api('horoscopes/'+selected.month+'/unpublish','POST',{revision:selected.revision});form(selected);await refresh();el('message').textContent='Month unpublished; draft retained.';});
root.addEventListener('click',e=>{const b=e.target.closest('[data-member-state]');if(!b)return;run(async()=>{await api('members/'+b.dataset.memberState+'/preview','POST',{status:el('state-'+b.dataset.memberState).value});await refresh();el('message').textContent='Preview state updated. No payment or email occurred.';})();});
window.loadMembershipAdmin=run(refresh);document.querySelector('[data-tab="admin-membership"]')?.addEventListener('click',window.loadMembershipAdmin);form();
})();
