const A=require('astronomy-engine'),moment=require('moment-timezone'),fs=require('fs'),zlib=require('zlib'),path=require('path');
const signs=['Aries','Taurus','Gemini','Cancer','Leo','Virgo','Libra','Scorpio','Sagittarius','Capricorn','Aquarius','Pisces'];
const bodies=['Sun','Moon','Rising','Mercury','Jupiter','Mars','Venus'];
const meanings={Sun:'In astrology, the Sun describes identity, vitality, and the qualities you grow into. Read this sign’s horoscope through the lens of your sense of self and the choices that feel meaningful to you.',Moon:'The Moon represents emotional needs, familiar responses, and what helps you feel at home. Read this sign’s horoscope as a reflection on feelings, care, and your inner life.',Rising:'The Rising sign describes your approach to new experiences and how you meet the world. Many sign-based horoscopes are organized with the Rising sign in mind; use it as another perspective alongside your Sun and Moon.',Mercury:'Mercury represents communication, learning, and how you process ideas. Approach its sign’s horoscope as a prompt to reflect on conversations, decisions, and your way of thinking.',Jupiter:'Jupiter represents growth, beliefs, and the search for meaning. Read this sign’s horoscope through the lens of learning, possibility, and the places where you want to grow.',Mars:'Mars represents initiative, motivation, and how you assert yourself. Use its sign’s horoscope to reflect on action, boundaries, and where you put your energy.',Venus:'Venus represents affection, pleasure, values, and how you connect. Read this sign’s horoscope through the lens of relationships, creativity, and what you appreciate.'};
let places;function allPlaces(){if(places)return places;const packed=Buffer.concat(['00','01','02','03'].map(part=>fs.readFileSync(path.join(__dirname,'places.json.gz.part-'+part))));return places=(JSON.parse(zlib.gunzipSync(packed))).map(p=>({...p,search:p.search.normalize('NFD').replace(/[\u0300-\u036f]/g,'')}));}
function searchPlaces(query){const terms=String(query||'').trim().toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').split(/[\s,]+/).filter(Boolean);if(!terms.length)return [];return allPlaces().filter(p=>terms.every(t=>p.search.includes(t))).slice(0,15).map(({id,label,zone})=>({id,label,zone}));}
const problem=m=>Object.assign(Error(m),{status:400});
function normalize(input){const date=String(input.date||'');if(!/^\d{4}-\d\d-\d\d$/.test(date)||!moment.utc(date,'YYYY-MM-DD',true).isValid()||date<'1900-01-01'||date>moment.utc().format('YYYY-MM-DD'))throw problem('Please enter a valid birth date from 1900 through today.');const time=input.unknownTime?null:String(input.time||'');if(time!==null&&!/^([01]\d|2[0-3]):[0-5]\d$/.test(time))throw problem('Enter a birth time or choose “Time unknown.”');let place=null;if(!input.unknownLocation){if(input.placeId){place=allPlaces().find(p=>p.id===String(input.placeId));if(!place)throw problem('Choose a birthplace from the search results.');place={id:place.id,label:place.label,lat:place.lat,lon:place.lon,zone:place.zone};}else if(input.customPlace){const c=input.customPlace,lat=Number(c.lat),lon=Number(c.lon);if(c.lat===''||c.lon===''||!Number.isFinite(lat)||!Number.isFinite(lon)||Math.abs(lat)>90||Math.abs(lon)>180||!moment.tz.zone(c.zone))throw problem('Check the coordinates and select a valid IANA time zone.');place={id:null,label:String(c.label||'Custom birthplace').slice(0,160),lat,lon,zone:c.zone};}else throw problem('Choose your birthplace, or select “Location unknown.”');}return {date,time,place,occurrence:['earlier','later'].includes(input.occurrence)?input.occurrence:'unknown'};}
function localCandidates(date,time,zone){const z=moment.tz.zone(zone),wall=Date.parse(date+'T'+time+':00Z');return [...new Set(z.offsets)].map(offset=>wall+offset*60000).filter(utc=>moment.tz(utc,zone).format('YYYY-MM-DD HH:mm')===date+' '+time).sort((a,b)=>a-b);}
function longitude(body,date){return body==='Moon'?A.EclipticGeoMoon(date).lon:A.Ecliptic(A.GeoVector(body,date,true)).elon;}
function rising(date,lat,lon){if(Math.abs(lat)>=66)return null;const rad=Math.PI/180,t=A.MakeTime(date),theta=(A.SiderealTime(t)*15+lon)*rad,phi=lat*rad;
 const rot=A.Rotation_ECT_EQD(t),x=A.RotateVector(rot,new A.Vector(1,0,0,t)),y=A.RotateVector(rot,new A.Vector(0,1,0,t));
 const zen=[Math.cos(phi)*Math.cos(theta),Math.cos(phi)*Math.sin(theta),Math.sin(phi)],east=[-Math.sin(theta),Math.cos(theta),0],dot=(a,v)=>a[0]*v.x+a[1]*v.y+a[2]*v.z;
 const angle=Math.atan2(-dot(zen,x),dot(zen,y));let value=angle/rad;if(dot(east,x)*Math.cos(angle)+dot(east,y)*Math.sin(angle)<0)value+=180;return (value+360)%360;}
function calculate(input){const profile=normalize(input),notes=[],dateUTC=Date.parse(profile.date+'T00:00:00Z');let instants=[],ambiguous=false,interval=false;
 if(profile.place&&profile.time){instants=localCandidates(profile.date,profile.time,profile.place.zone);if(!instants.length)throw problem('That local time did not occur because the clocks changed. Check the birth record, or choose “Time unknown.”');ambiguous=instants.length>1;if(ambiguous){if(profile.occurrence==='earlier')instants=[instants[0]];else if(profile.occurrence==='later')instants=[instants.at(-1)];else notes.push('The clocks repeated this time on your birth date. Results below allow for both occurrences; select the earlier or later occurrence only if your record confirms it.');}}
 else{interval=true;const start=dateUTC-16*3600000,end=dateUTC+40*3600000;for(let ms=start;ms<=end;ms+=15*60000){if(!profile.place||moment.tz(ms,profile.place.zone).format('YYYY-MM-DD')===profile.date)instants.push(ms);}if(!instants.length)throw problem('This date did not occur in the selected location because of a historical clock change. Check the birth date or location.');notes.push(profile.place?'Your time is unknown. A sign is shown only when it stays the same throughout your local birth date.':'Without a known location and time zone, we check a conservative worldwide time range for your birthday. Only placements that stay in one sign throughout that range are shown.');}
 if(profile.date<'1970-01-01')notes.push('Historical time-zone records before 1970 can be incomplete for some places. These results use the available IANA history; a boundary result may need a birth-record check.');
 notes.push('Western tropical zodiac. Birthplace calculations use the selected city’s coordinates; if your exact location is not listed, use the optional coordinates form. A result near a sign boundary is left uncertain.');
 const placements=bodies.map(body=>{const possible=new Set();let unavailable=false;if(body==='Rising'&&(!profile.time||!profile.place)){unavailable=true;}else if(body==='Rising'&&Math.abs(profile.place.lat)>=66){unavailable=true;notes.push('Rising is not shown for polar latitudes, where the horizon geometry needs specialist checking.');}else{for(const ms of instants){const samples=body==='Rising'?[-300000,0,300000]:[0];for(const delta of samples){const value=body==='Rising'?rising(new Date(ms+delta),profile.place.lat,profile.place.lon):longitude(body,new Date(ms));const margin=body==='Rising'?0.1:interval?0.3:0.06;for(const shift of [-margin,0,margin])possible.add(signs[Math.floor(((value+shift+360)%360)/30)]);}}}
  return {placement:body,sign:!unavailable&&possible.size===1?[...possible][0]:null,reliable:!unavailable&&possible.size===1,possibleSigns:unavailable?[]:[...possible],explanation:meanings[body],note:unavailable?'A reliable Rising sign needs a known birth time and location.':possible.size>1?'This placement may change signs within the possible birth-time range or lies close to a boundary. More precise details may help.':body==='Rising'?'Stable across a five-minute margin on either side of the entered time.':''};});
 return {profile,placements,notes,ambiguous,calculatedAt:new Date().toISOString(),method:{engine:'Astronomy Engine 2.1.19',zodiac:'tropical',timezoneData:moment.tz.dataVersion}};
}
function matchingReading(chart,month){const groups=[];for(const p of chart?.placements||[]){if(!p.reliable||!p.sign||!month?.content?.[p.sign])continue;let g=groups.find(x=>x.sign===p.sign);if(!g){g={sign:p.sign,content:month.content[p.sign],placements:[]};groups.push(g);}g.placements.push({placement:p.placement,explanation:p.explanation});}return groups;}
module.exports={calculate,normalize,localCandidates,longitude,rising,searchPlaces,matchingReading,signs,meanings};
