(()=>{
const root=document.getElementById('app'),feedback=document.getElementById('feedback');
const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const api=async(p,method='GET',body)=>{const r=await fetch('/api/membership/'+p,{method,headers:{'Content-Type':'application/json'},body:body?JSON.stringify(body):undefined});const x=await r.json();if(!r.ok)throw Object.assign(Error(x.error),{status:r.status});return x;};
const date=x=>x?new Date(x).toLocaleString():'Not applicable — no paid subscription';
const act=fn=>async e=>{e?.preventDefault();const b=e?.target?.querySelector?.('button')||e?.target;if(b)b.disabled=true;feedback.textContent='';try{await fn(e);}catch(err){feedback.textContent=err.message;}finally{if(b)b.disabled=false;}};
function auth(email){root.innerHTML=`<section class="card"><h2>Welcome to your members area</h2><p>Create a separate membership login for the private preview. Existing bookings and newsletter preferences stay as they are.</p><form id="signup"><h3>Create your account</h3><label for="name">Name</label><input id="name" name="name" autocomplete="name" required><label for="email">Email</label><input id="email" name="email" type="email" value="${esc(email)}" autocomplete="email" required><label for="new-password">Password (at least 8 characters)</label><input id="new-password" name="member_password" type="password" minlength="8" maxlength="200" autocomplete="new-password" required><div class="hp" aria-hidden="true"><label>Website<input name="website" tabindex="-1" autocomplete="off"></label></div><div class="actions"><button>Create account &amp; send confirmation</button></div></form></section><section class="card"><form id="login"><h2>Already registered?</h2><label for="login-email">Email</label><input id="login-email" name="email" type="email" value="${esc(email)}" autocomplete="username" required><label for="login-password">Password</label><input id="login-password" name="member_password" type="password" autocomplete="current-password" required><div class="actions"><button>Sign in</button><button type="button" id="forgot">Send password reset</button></div></form></section>`;
for(const id of ['signup','login'])document.getElementById(id).onsubmit=act(async e=>{const x=await api(id,'POST',Object.fromEntries(new FormData(e.target)));await load();feedback.textContent=x.message||'Signed in.';});
document.getElementById('forgot').onclick=act(async()=>{feedback.textContent=(await api('forgot','POST',{email:document.getElementById('login-email').value})).message;});}
function account(m){root.innerHTML=`<section class="card"><h2>Hello, ${esc(m.name)}</h2><dl><dt>Email</dt><dd>${esc(m.email)}</dd><dt>Email confirmed</dt><dd>${m.verified?'Yes':'Not yet'}</dd><dt>Membership tier</dt><dd>Luce Healing Membership — private preview</dd><dt>Status</dt><dd>${esc(m.status.replaceAll('_',' '))}</dd><dt>Access through</dt><dd>${date(m.access_until)}</dd><dt>Billing period start</dt><dd>${date(m.billing_period_start)}</dd><dt>${m.cancel_at_period_end?'Cancellation effective':'Next billing date / period end'}</dt><dd>${date(m.billing_period_end)}</dd></dl>${m.cancel_at_period_end?'<p>Cancellation is scheduled. Access continues through the end of your paid period.</p>':''}<p class="note">Preview access is not a paid subscription. Membership pricing awaits Christina’s confirmation.</p><div class="actions">${!m.verified?'<button id="resend">Resend confirmation email</button>':''}<button id="portal">Manage billing / cancel</button><button id="reset">Send password reset</button><button id="logout">Sign out</button></div><p class="muted">${m.portal_available?'Billing management opens securely in Stripe’s sandbox.':'Stripe sandbox billing is not connected yet. This preview cannot create live charges.'}</p></section>`;
if(!m.verified)document.getElementById('resend').onclick=act(async()=>feedback.textContent=(await api('resend','POST',{})).message);
document.getElementById('portal').onclick=act(async()=>{const x=await api('portal','POST',{});location.assign(x.url);});document.getElementById('reset').onclick=act(async()=>feedback.textContent=(await api('forgot','POST',{email:m.email})).message);document.getElementById('logout').onclick=act(async()=>{await api('logout','POST',{});await load();});}
async function load(){const page=location.pathname.split('/').pop();if(['verify','reset'].includes(page)){const t=new URLSearchParams(location.search).get('token');history.replaceState(null,'',location.pathname);root.innerHTML=`<section class="card"><h2>${page==='verify'?'Confirm your member account':'Choose a new password'}</h2><form id="token-form">${page==='reset'?'<label for="reset-password">New password (at least 8 characters)</label><input id="reset-password" type="password" minlength="8" maxlength="200" autocomplete="new-password" required>':'<p>Confirm to activate your private preview. No payment is required.</p>'}<div class="actions"><button>${page==='verify'?'Confirm my account':'Save new password'}</button></div></form><p><a href="/members">Back to members</a> · <a href="/members/review">Open private preview</a></p></section>`;document.getElementById('token-form').onsubmit=act(async()=>{const x=await api(page,'POST',{token:t,member_password:document.getElementById('reset-password')?.value});feedback.textContent=x.message;document.getElementById('token-form').hidden=true;});return;}
const config=await api('config');if(page==='information'){root.innerHTML=`<section class="card"><h2>Monthly astrology, in one quiet place</h2><p>Read monthly horoscopes for all twelve zodiac signs. Explore your Sun, Moon, and Rising signs, or spend time with any sign that interests you.</p><p>New monthly content is written and published by Christina. Drafts remain private until she publishes them to members.</p><h3>One Luce Healing membership</h3><p>Read every sign, save your private birth details, and bring together Christina’s published horoscopes through the lens of your reliable birth-chart placements.</p><p>Pricing is still to be confirmed.</p><p class="note">This is a private information-page draft. Enrollment and checkout are disabled. No membership price or additional benefit is promised here.</p><p>Planned account features include secure billing management, cancellation through Stripe, and access through the end of a paid period.</p></section>`;return;}
let m;try{m=await api('me');}catch(e){if(e.status!==401)throw e;auth(config.testEmail);return;}
if(page==='chart'){await birthChart();return;}
if(page==='account'||!m.access){account(m);return;}
await readings(config,page==='reading');}
function monthChoices(months){const current=new Date().toLocaleDateString('en-CA',{timeZone:'America/Los_Angeles',year:'numeric',month:'2-digit'}).slice(0,7);const actual=months.filter(m=>!m.demo).sort((a,b)=>b.month.localeCompare(a.month))[0];return {current,selected:actual?.month||current};}
async function readings(config,personal){const months=await api('horoscopes'),choice=monthChoices(months);const qs=new URLSearchParams(location.search);let selected=qs.get('month')||choice.selected;let sign=config.signs.includes(qs.get('sign'))?qs.get('sign'):'Aries';
root.innerHTML=`<section class="card"><h2>${personal?'My monthly reading':'Your monthly horoscopes'}</h2><p>${personal?'Your reliable placements, matched to Christina’s published sign horoscopes. This is a reading guide assembled from shared content, not an individually written consultation.':'Choose any sign. You can explore your Sun, Moon, Rising, and every other sign.'}</p>${!personal?`<label for="sign">Choose a sign</label><select id="sign">${config.signs.map(s=>`<option${s===sign?' selected':''}>${s}</option>`).join('')}</select>`:''}<p id="month-label"></p><details><summary>Other published months / archive</summary><label for="archive">Select a published month</label><select id="archive"><option value="${choice.current}">Current month — ${choice.current}</option>${months.filter(x=>x.month!==choice.current).map(x=>`<option value="${x.month}">${esc(x.title)} (${x.demo?'demonstration':x.month})</option>`).join('')}</select></details></section><div id="readings"></div>`;
const archive=document.getElementById('archive');if([...archive.options].some(o=>o.value===selected))archive.value=selected;else selected=choice.current;
const show=async()=>{selected=archive.value;const m=months.find(x=>x.month===selected);document.getElementById('month-label').textContent='Month: '+new Date(selected+'-15T12:00:00Z').toLocaleDateString(undefined,{month:'long',year:'numeric'});const target=document.getElementById('readings');if(!m){target.innerHTML='<section class="card"><p>Christina has not published this month yet. You can choose another published month in the archive above.</p></section>';return;}const banner=m.demo?'<p class="note">DEMONSTRATION CONTENT — for interface review only. These are not actual monthly forecasts.</p>':'';if(personal){const result=await api('reading?month='+encodeURIComponent(selected));target.innerHTML=banner+(result.groups.length?result.groups.map(g=>`<article class="card"><h2>${esc(g.sign)}</h2>${g.placements.map(p=>`<h3>${esc(p.placement)} in ${esc(g.sign)}</h3><p>${esc(p.explanation)}</p>`).join('')}<h3>Christina’s published horoscope</h3><div class="horoscope">${esc(g.content)}</div><p><a href="/members?sign=${encodeURIComponent(g.sign)}&month=${selected}">Read the ${esc(g.sign)} horoscope</a></p></article>`).join(''):'<section class="card"><p>Add your birth details to build this view. Only reliable placements with a published horoscope are included.</p><a class="button" href="/members/chart">My birth chart</a></section>');}else{sign=document.getElementById('sign').value;target.innerHTML=banner+`<article class="card"><h2>${esc(sign)}</h2><p class="muted">${esc(m.title)}</p><div class="horoscope">${esc(m.content[sign]||'No published text for this sign.')}</div><p><a href="#sign">Back to sign selector</a></p></article>`;}};
archive.onchange=()=>show().catch(e=>feedback.textContent=e.message);if(!personal)document.getElementById('sign').onchange=()=>show().catch(e=>feedback.textContent=e.message);await show();}
async function birthChart(){const saved=await api('chart'),p=saved.profile||{};let place=p.place,chart=saved.chart;
root.innerHTML=`<section class="card"><h2>My birth chart</h2><p>Your birth details are private to your member account. You can update or remove them at any time.</p><form id="birth-form"><label for="birth-date">Birth date</label><input id="birth-date" type="date" min="1900-01-01" value="${esc(p.date||'')}" required><label><input id="unknown-time" type="checkbox" ${!p.time?'checked':''}> Time unknown</label><label for="birth-time">Birth time (local clock time)</label><input id="birth-time" type="time" value="${esc(p.time||'')}"><label><input id="unknown-place" type="checkbox" ${!p.place?'checked':''}> Location unknown</label><div id="place-fields"><label for="place-search">Birthplace — city or town, region, country</label><input id="place-search" type="search" placeholder="For example: Los Angeles, California"><button type="button" id="place-find">Find birthplace</button><label for="place-results">Choose the correct location</label><select id="place-results"><option value="">Search and select a birthplace</option></select><p id="selected-place" class="muted">${p.place?esc(p.place.label)+' · '+esc(p.place.zone):''}</p><details><summary>My place is not listed — enter exact coordinates</summary><p class="muted">Use this only if you know the coordinates and historical IANA time-zone region. Otherwise choose Location unknown; we will still show reliable basic placements.</p><label for="custom-name">Place name</label><input id="custom-name"><label for="custom-lat">Latitude (north positive, south negative)</label><input id="custom-lat" type="number" step="any" min="-90" max="90"><label for="custom-lon">Longitude (east positive, west negative)</label><input id="custom-lon" type="number" step="any" min="-180" max="180"><label for="custom-zone">IANA time zone, for example America/Los_Angeles</label><input id="custom-zone"><button type="button" id="custom-use">Use these coordinates</button></details></div><details><summary>If your birth time happened twice during a clock change</summary><label for="occurrence">Which occurrence does the birth record specify?</label><select id="occurrence"><option value="unknown">I don’t know — allow for both</option><option value="earlier">Earlier occurrence</option><option value="later">Later occurrence</option></select></details><div class="actions"><button>Save details &amp; calculate</button><button id="birth-delete" type="button">Remove my birth details</button></div></form><p class="muted">Western tropical zodiac · Calculated locally using Astronomy Engine and historical IANA time zones. City data: <a href="https://www.geonames.org/" target="_blank" rel="noopener noreferrer">GeoNames</a> (CC BY 4.0). No birth details are sent to a chart or AI service.</p></section><div id="placements"></div>`;
const el=id=>document.getElementById(id);el('occurrence').value=p.occurrence||'unknown';const toggles=()=>{el('birth-time').disabled=el('unknown-time').checked;el('place-fields').hidden=el('unknown-place').checked;};el('unknown-time').onchange=toggles;el('unknown-place').onchange=toggles;toggles();
el('place-find').onclick=act(async()=>{const results=await api('places?q='+encodeURIComponent(el('place-search').value));el('place-results').innerHTML='<option value="">Select the correct birthplace</option>'+results.map(x=>`<option value="${x.id}">${esc(x.label)} — ${esc(x.zone)}</option>`).join('');if(!results.length)feedback.textContent='No matching city was found. Try a nearby city only if its location is appropriate, use exact coordinates, or select Location unknown.';el('place-results').onchange=()=>{const found=results.find(x=>x.id===el('place-results').value);if(found){place=found;el('selected-place').textContent=found.label+' · '+found.zone;}};});
el('custom-use').onclick=()=>{place={id:null,label:el('custom-name').value,lat:el('custom-lat').value,lon:el('custom-lon').value,zone:el('custom-zone').value};el('selected-place').textContent='Custom place: '+place.label+' · '+place.zone;};
const show=()=>{el('placements').innerHTML=chart?`<section class="card"><h2>Your placements</h2>${chart.notes.map(n=>`<p class="muted">${esc(n)}</p>`).join('')}</section>`+chart.placements.map(x=>`<article class="card"><h2>${esc(x.placement)}${x.reliable?' in '+esc(x.sign):' — more details needed'}</h2><p>${esc(x.explanation)}</p>${x.note?`<p class="muted">${esc(x.note)}</p>`:''}${x.reliable?`<a class="button" href="/members?sign=${encodeURIComponent(x.sign)}">Read ${esc(x.sign)} this month</a>`:''}</article>`).join(''):'';};show();
el('birth-form').onsubmit=act(async()=>{const result=await api('chart','PUT',{date:el('birth-date').value,time:el('birth-time').value,unknownTime:el('unknown-time').checked,unknownLocation:el('unknown-place').checked,placeId:place?.id,customPlace:place&&!place.id?place:undefined,occurrence:el('occurrence').value});chart=result.chart;place=result.profile.place;show();feedback.textContent='Birth details saved and placements calculated.';});el('birth-delete').onclick=act(async()=>{if(!confirm('Remove your saved birth details and calculated placements?'))return;await api('chart','DELETE',{});await birthChart();feedback.textContent='Birth details removed.';});}

load().catch(e=>{feedback.textContent=e.message;root.innerHTML='<section class="card"><a class="button" href="/members/review">Open private preview with Admin</a></section>';});
})();
