(()=>{
const root=document.getElementById('app'),feedback=document.getElementById('feedback');
const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const api=async(p,method='GET',body)=>{const r=await fetch('/api/membership/'+p,{method,headers:{'Content-Type':'application/json'},body:body?JSON.stringify(body):undefined});const x=await r.json();if(!r.ok)throw Object.assign(Error(x.error),{status:r.status});return x;};
const date=x=>x?new Date(x).toLocaleString():'Not applicable — no paid subscription';
const act=fn=>async e=>{e?.preventDefault();const b=e?.target?.querySelector?.('button')||e?.target;if(b)b.disabled=true;feedback.textContent='';try{await fn(e);}catch(err){feedback.textContent=err.message;}finally{if(b)b.disabled=false;}};
function auth(email,config){root.innerHTML=`<section class="card"><h2>Welcome to your members area</h2><p>${config.private?'Create a separate login for the private membership preview.':'Create your Astrology Membership account, confirm your email, then choose a subscription.'}</p><form id="signup"><h3>Create your account</h3><label for="name">Name</label><input id="name" name="name" autocomplete="name" required><label for="email">Email</label><input id="email" name="email" type="email" value="${esc(email)}" autocomplete="email" required><label for="new-password">Password (at least 8 characters)</label><input id="new-password" name="member_password" type="password" minlength="8" maxlength="200" autocomplete="new-password" required><div class="hp" aria-hidden="true"><label>Website<input name="website" tabindex="-1" autocomplete="off"></label></div>${config.private?'':'<div id="membership-security"></div>'}<div class="actions"><button>Create account &amp; send confirmation</button></div></form></section><section class="card"><form id="login"><h2>Already registered?</h2><label for="login-email">Email</label><input id="login-email" name="email" type="email" value="${esc(email)}" autocomplete="username" required><label for="login-password">Password</label><input id="login-password" name="member_password" type="password" autocomplete="current-password" required><div class="actions"><button>Sign in</button><button type="button" id="forgot">Send password reset</button></div></form></section>`;
let securityWidget;
if(!config.private){const render=()=>{securityWidget=window.turnstile.render('#membership-security',{sitekey:config.turnstileSiteKey,action:'membership_signup'});};if(window.turnstile)render();else{const script=document.createElement('script');script.src='https://challenges.cloudflare.com/turnstile/v0/api.js?render=explicit';script.onload=render;script.onerror=()=>feedback.textContent='Security check could not load. Please refresh.';document.head.append(script);}}
for(const id of ['signup','login'])document.getElementById(id).onsubmit=act(async e=>{const body=Object.fromEntries(new FormData(e.target));if(id==='signup'&&!config.private)body.turnstile_token=window.turnstile?.getResponse(securityWidget)||'';try{const x=await api(id,'POST',body);await load();feedback.textContent=x.message||'Signed in.';}catch(err){if(id==='signup'&&!config.private&&securityWidget!==undefined)window.turnstile.reset(securityWidget);throw err;}});
document.getElementById('forgot').onclick=act(async()=>{feedback.textContent=(await api('forgot','POST',{email:document.getElementById('login-email').value})).message;});}
function account(m,config){root.innerHTML=`<section class="card"><h2>Hello, ${esc(m.name)}</h2><dl><dt>Email</dt><dd>${esc(m.email)}</dd><dt>Email confirmed</dt><dd>${m.verified?'Yes':'Not yet'}</dd><dt>Membership tier</dt><dd>${m.is_test?'Astrology Membership — private preview':'Astrology Membership'}</dd><dt>Status</dt><dd>${esc(m.status.replaceAll('_',' '))}</dd><dt>Access through</dt><dd>${date(m.access_until)}</dd><dt>Billing period start</dt><dd>${date(m.billing_period_start)}</dd><dt>${m.cancel_at_period_end?'Cancellation effective':'Next billing date / period end'}</dt><dd>${date(m.billing_period_end)}</dd></dl>${m.cancel_at_period_end?'<p>Cancellation is scheduled. Access continues through the end of your paid period.</p>':''}<p class="note">${m.is_test?'This is your test account. Test payments do not start a real subscription.':'Manage your subscription securely through Stripe. Cancel anytime; access continues through the end of your paid period.'} <a href="/astrology-membership">View membership pricing</a>.</p><div class="actions">${!m.verified?'<button id="resend">Resend confirmation email</button>':''}<button id="portal">Manage billing / cancel</button><button id="reset">Send password reset</button><button id="logout">Sign out</button></div><p class="muted">${m.portal_available?(m.is_test?'Billing management opens securely in Stripe’s sandbox.':'Billing management opens securely in Stripe.'):'Choose a subscription after confirming your email.'}</p></section>`;
if(m.verified&&((m.is_test&&config.testCheckoutEnabled)||(!m.is_test&&config.purchasingEnabled&&!m.access))){
 const box=document.createElement('section');box.className='card';box.innerHTML=`<h2>${m.is_test?'Private payment test':'Choose your membership'}</h2>${!m.is_test&&!config.latestMonth&&config.nextPublication?`<p>Readings are scheduled for ${esc(new Date(config.nextPublication.scheduled_at).toLocaleString('en-US',{timeZone:'America/Los_Angeles',dateStyle:'long',timeStyle:'short'}))} Pacific Time.</p>`:''}<p>${m.is_test?'Stripe test mode only. Use test card details.':'Recurring subscription. Cancel anytime through My account. Annual membership is paid upfront.'}</p><div class="actions"><button data-plan="monthly">${m.is_test?'Test Join':'Join'} — ${config.foundingOfferOpen?'$2.95/month founding':'$3.95/month'}</button><button data-plan="annual">${m.is_test?'Test Join':'Join'} — $37.92/year</button></div>`;root.append(box);
 box.querySelectorAll('[data-plan]').forEach(b=>b.onclick=act(async()=>{const x=await api('checkout','POST',{plan:b.dataset.plan});location.assign(x.url);}));
}
if(new URLSearchParams(location.search).get('checkout')==='success'&&m.status!=='active')feedback.textContent='Checkout returned. Payment confirmation is still pending; refresh your account shortly.';
if(!m.verified)document.getElementById('resend').onclick=act(async()=>feedback.textContent=(await api('resend','POST',{})).message);
document.getElementById('portal').onclick=act(async()=>{const x=await api('portal','POST',{});location.assign(x.url);});document.getElementById('reset').onclick=act(async()=>feedback.textContent=(await api('forgot','POST',{email:m.email})).message);document.getElementById('logout').onclick=act(async()=>{await api('logout','POST',{});await load();});}
async function load(){const page=location.pathname.split('/').pop();if(['verify','reset'].includes(page)){const t=new URLSearchParams(location.search).get('token');history.replaceState(null,'',location.pathname);root.innerHTML=`<section class="card"><h2>${page==='verify'?'Confirm your member account':'Choose a new password'}</h2><form id="token-form">${page==='reset'?'<label for="reset-password">New password (at least 8 characters)</label><input id="reset-password" type="password" minlength="8" maxlength="200" autocomplete="new-password" required>':'<p>Confirm your email to continue to your member account. Payment is a separate step.</p>'}<div class="actions"><button>${page==='verify'?'Confirm my account':'Save new password'}</button></div></form><p><a href="/members">Back to members</a></p></section>`;document.getElementById('token-form').onsubmit=act(async()=>{const x=await api(page,'POST',{token:t,member_password:document.getElementById('reset-password')?.value});feedback.textContent=x.message;document.getElementById('token-form').hidden=true;const next=document.createElement('a');next.className='button';next.href='/members/account';next.textContent='Continue to My account';root.append(next);});return;}
const config=await api('config');const mode=document.getElementById('membership-mode');if(mode)mode.textContent=config.private?'Private membership preview · No live purchases':'Monthly guidance for every sign';if(page==='information'&&!config.private){location.replace('/astrology-membership');return;}if(page==='information'){root.innerHTML=`<section class="card" aria-label="Private placement preview"><p class="muted">Future website placement · Private preview only</p><h2>Main dropdown menu</h2><details><summary>Menu</summary><nav aria-label="Proposed membership menu item"><a href="#membership-details">Astrology Membership</a></nav></details><h2>Homepage section</h2><section aria-label="Proposed homepage membership section"><h3>Astrology Membership</h3><p>A little space for the month ahead. Explore monthly horoscopes for every sign, discover your birth-chart placements, and return to the guidance that speaks to you.</p><a class="button" href="#membership-details">Explore Astrology Membership</a></section><p class="muted">One homepage section, with full pricing and details on the Astrology Membership page.</p></section><section class="card" id="membership-details"><h2>Monthly astrology, in one quiet place</h2><p>Read monthly horoscopes for all twelve zodiac signs. Explore your Sun, Moon, and Rising signs, or spend time with any sign that interests you.</p><p>New monthly content is written and published by Christina. Drafts remain private until she publishes them to members.</p><h3>Astrology Membership</h3><p>Read every sign, save your private birth details, and bring together Christina’s published horoscopes through the lens of your reliable birth-chart placements.</p><h3>Founding Member — special launch price</h3><p><strong>$2.95/month</strong> · Cancel anytime.</p><p>Available to people who join during the founding period. Your $2.95 monthly rate stays locked in for as long as your membership remains continuously active. If you cancel and later rejoin after the founding offer has ended, the current regular price will apply.</p><p class="muted">The founding offer is monthly only. At $35.40 over 12 months, it is already less than the regular annual plan.</p><h3>Regular membership</h3><p><strong>$3.95/month</strong> · Cancel anytime.</p><p><strong>$37.92/year</strong> · Paid upfront. Save 20% compared with 12 months at the regular monthly price ($47.40).</p><p class="note">Private pricing preview only. Enrollment and checkout remain disabled; no payments are being taken.</p><p>Planned account features include secure billing management, cancellation through Stripe, and access through the end of a paid period.</p></section>`;return;}
let m;try{m=await api('me');}catch(e){if(e.status!==401)throw e;auth(config.testEmail,config);return;}
if(page==='chart'){await birthChart();return;}
if(page==='account'||!m.access){account(m,config);return;}
await readings(config,page==='reading');}
function collectionTitle(m){return !m.title||/^(Current month(?: — \d{4}-\d{2})?|Demonstration month|Monthly Horoscopes \(\d{4}-\d{2}\))$/i.test(m.title)?new Date((m.display_month||m.month)+'-15T12:00:00Z').toLocaleDateString('en-US',{month:'long',year:'numeric'})+' Horoscopes':m.title;}
function readingPanel(title,body,open=false){return `<details class="card"${open?' open':''}><summary style="cursor:pointer;padding:8px 0;font-size:1.2rem;font-weight:600;color:#624373">${esc(title)}</summary><div style="padding-top:16px">${body}</div></details>`;}
async function readings(config,personal){
 const months=(await api('horoscopes')).filter(m=>!m.demo).map(m=>({...m,title:collectionTitle(m)}));
 months.sort((a,b)=>(new Date(b.published_at||0)-new Date(a.published_at||0))||b.month.localeCompare(a.month));
 const monthly=months.filter(m=>m.collection_type!=='special'),special=months.filter(m=>m.collection_type==='special');
 const featured=monthly.find(m=>m.featured_at)||monthly[0],previous=monthly.filter(m=>m!==featured),qs=new URLSearchParams(location.search);let selected=months.find(m=>m.month===qs.get('month'))?.month||featured?.month;
 root.innerHTML=`<section class="card"><h2>${personal?'My monthly reading':'Your monthly horoscopes'}</h2><p>${personal?'Your birth-chart placements guide you to Christina’s published horoscopes. Forecast text comes directly from her readings, with no outside forecasts added. Short explanations of traditional Western astrology help you explore each placement. Tap a heading to open its reading.':'The general monthly reading comes first, followed by all 12 zodiac signs. Tap a heading to open or close its reading.'}</p>${featured?`<p class="muted">Featured horoscopes</p><h3>${esc(featured.title)}</h3>${featured.subtitle?`<p>${esc(featured.subtitle)}</p>`:''}<button data-open-month="${featured.month}">Open ${esc(featured.title)}</button>`:'<p>Your monthly readings will appear here when published.</p>'}${previous.length?`<details style="margin-top:24px"><summary>Previous Months</summary><div class="actions">${previous.map(m=>`<button data-open-month="${m.month}">${esc(m.title)}</button>`).join('')}</div></details>`:''}${special.length?`<section id="special-guidance" style="margin-top:24px"><h3>Special Astrology Guidance</h3><div class="actions">${special.map(m=>`<button data-open-month="${m.month}">${esc(m.title)}</button>`).join('')}</div></section>`:''}<h2 id="month-label"></h2><p id="month-subtitle"></p></section><div id="readings"></div>`;
 let renderVersion=0;
 const show=async()=>{
  const version=++renderVersion;const m=months.find(x=>x.month===selected),month=selected;
  const monthLabel=m?.title||'';
  document.getElementById('month-label').textContent=monthLabel;document.getElementById('month-subtitle').textContent=m?.subtitle||'';root.querySelectorAll('[data-open-month]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.openMonth===selected)));
  const target=document.getElementById('readings');
  if(!m){target.innerHTML='';return;}
  const banner='';
  const general=m.content.General?.trim()?readingPanel(monthLabel+' — General reading for all signs',`<div class="horoscope">${esc(m.content.General)}</div>`):'';
  target.innerHTML=banner+general;
  if(personal){
   const result=await api('reading?month='+encodeURIComponent(month));if(version!==renderVersion)return;
   target.innerHTML=banner+general+(result.groups.length?result.groups.map(g=>readingPanel(g.sign,g.placements.map(p=>`<h3>${esc(p.placement)} in ${esc(g.sign)}</h3><p>${esc(p.explanation)}</p>`).join('')+`<h3>Christina’s published horoscope</h3><div class="horoscope">${esc(g.content)}</div><p><a href="/members?sign=${encodeURIComponent(g.sign)}&month=${month}">Read the ${esc(g.sign)} horoscope</a></p>`)).join(''):'<section class="card"><p>Add your birth details to build this view. Only reliable placements with a published horoscope are included.</p><a class="button" href="/members/chart">My birth chart</a></section>');
  }else target.innerHTML=banner+general+config.signs.map(sign=>readingPanel(sign,`<p class="muted">${esc(m.title)}</p><div class="horoscope">${esc(m.content[sign]||'No published text for this sign.')}</div>`,qs.get('sign')===sign)).join('');
 };
 root.querySelectorAll('[data-open-month]').forEach(b=>b.onclick=act(async()=>{selected=b.dataset.openMonth;await show();document.getElementById('month-label').scrollIntoView({behavior:'smooth',block:'start'});}));await show();
}
async function birthChart(){const saved=await api('chart'),p=saved.profile||{};let place=p.place,chart=saved.chart;
root.innerHTML=`<section class="card"><h2>My birth chart</h2><p>Your birth details are private to your member account. You can update or remove them at any time.</p><form id="birth-form"><label for="birth-date">Birth date</label><input id="birth-date" type="date" min="1900-01-01" value="${esc(p.date||'')}" required><label><input id="unknown-time" type="checkbox" ${!p.time?'checked':''}> Time unknown</label><label for="birth-time">Birth time (local clock time)</label><input id="birth-time" type="time" value="${esc(p.time||'')}"><label><input id="unknown-place" type="checkbox" ${!p.place?'checked':''}> Location unknown</label><div id="place-fields"><label for="place-search">Birthplace — city or town, region, country</label><input id="place-search" type="search" placeholder="For example: Los Angeles, California"><button type="button" id="place-find">Find birthplace</button><label for="place-results">Choose the correct location</label><select id="place-results"><option value="">Search and select a birthplace</option></select><p id="selected-place" class="muted">${p.place?esc(p.place.label)+' · '+esc(p.place.zone):''}</p><details><summary>My place is not listed — enter exact coordinates</summary><p class="muted">Use this only if you know the coordinates and historical IANA time-zone region. Otherwise choose Location unknown; we will still show reliable basic placements.</p><label for="custom-name">Place name</label><input id="custom-name"><label for="custom-lat">Latitude (north positive, south negative)</label><input id="custom-lat" type="number" step="any" min="-90" max="90"><label for="custom-lon">Longitude (east positive, west negative)</label><input id="custom-lon" type="number" step="any" min="-180" max="180"><label for="custom-zone">IANA time zone, for example America/Los_Angeles</label><input id="custom-zone"><button type="button" id="custom-use">Use these coordinates</button></details></div><details><summary>If your birth time happened twice during a clock change</summary><label for="occurrence">Which occurrence does the birth record specify?</label><select id="occurrence"><option value="unknown">I don’t know — allow for both</option><option value="earlier">Earlier occurrence</option><option value="later">Later occurrence</option></select></details><div class="actions"><button>Save details &amp; calculate</button><button id="birth-delete" type="button">Remove my birth details</button></div></form><p class="muted">Western tropical zodiac · Calculated locally using Astronomy Engine and historical IANA time zones. City data: <a href="https://www.geonames.org/" target="_blank" rel="noopener noreferrer">GeoNames</a> (CC BY 4.0). No birth details are sent to a chart or AI service.</p></section><div id="placements"></div>`;
const el=id=>document.getElementById(id);el('occurrence').value=p.occurrence||'unknown';const toggles=()=>{el('birth-time').disabled=el('unknown-time').checked;el('place-fields').hidden=el('unknown-place').checked;};el('unknown-time').onchange=toggles;el('unknown-place').onchange=toggles;toggles();
let searchVersion=0;
const clearPlace=()=>{place=null;el('selected-place').textContent='';el('place-results').innerHTML='<option value="">Search and select a birthplace</option>';};
el('place-search').oninput=()=>{searchVersion++;clearPlace();};
el('place-find').onclick=act(async()=>{
 const version=++searchVersion;clearPlace();
 const results=await api('places?q='+encodeURIComponent(el('place-search').value));if(version!==searchVersion)return;
 el('place-results').innerHTML='<option value="">Select the correct birthplace</option>'+results.map(x=>`<option value="${esc(x.id)}">${esc(x.label)} — ${esc(x.zone)}</option>`).join('');
 const selectPlace=()=>{place=results.find(x=>String(x.id)===el('place-results').value)||null;el('selected-place').textContent=place?place.label+' · '+place.zone:'';};
 el('place-results').onchange=selectPlace;
 if(results.length===1){el('place-results').value=String(results[0].id);selectPlace();feedback.textContent='Birthplace selected: '+place.label+'. You can now save and calculate.';}
 else feedback.textContent=results.length?'Choose your city, region, and country from the results below.':'No matching city was found. Check the spelling or try the city and region without the country.';
});
el('custom-use').onclick=()=>{place={id:null,label:el('custom-name').value,lat:el('custom-lat').value,lon:el('custom-lon').value,zone:el('custom-zone').value};el('selected-place').textContent='Custom place: '+place.label+' · '+place.zone;};
const show=()=>{el('placements').innerHTML=chart?`<section class="card"><h2>Your placements</h2><p>These explanations describe traditional meanings in Western astrology. Use them as a guide to reflection alongside Christina’s monthly readings.</p>${chart.notes.map(n=>`<p class="muted">${esc(n)}</p>`).join('')}</section>`+chart.placements.map(x=>`<article class="card"><h2>${esc(x.placement)}${x.reliable?' in '+esc(x.sign):' — more details needed'}</h2><p>${esc(x.explanation)}</p>${x.note?`<p class="muted">${esc(x.note)}</p>`:''}${x.reliable?`<a class="button" href="/members?sign=${encodeURIComponent(x.sign)}">Read ${esc(x.sign)} this month</a>`:''}</article>`).join(''):'';};show();
el('birth-form').onsubmit=act(async()=>{const result=await api('chart','PUT',{date:el('birth-date').value,time:el('birth-time').value,unknownTime:el('unknown-time').checked,unknownLocation:el('unknown-place').checked,placeId:place?.id,customPlace:place&&!place.id?place:undefined,occurrence:el('occurrence').value});chart=result.chart;place=result.profile.place;show();feedback.textContent='Birth details saved and placements calculated.';});el('birth-delete').onclick=act(async()=>{if(!confirm('Remove your saved birth details and calculated placements?'))return;await api('chart','DELETE',{});await birthChart();feedback.textContent='Birth details removed.';});}

load().catch(e=>{feedback.textContent=e.message;root.innerHTML='<section class="card"><a class="button" href="/members/review">Open private preview with Admin</a></section>';});
})();

