(()=>{
const root=document.getElementById('app'),feedback=document.getElementById('feedback');
const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const api=async(p,method='GET',body)=>{const r=await fetch('/api/membership/'+p,{method,headers:{'Content-Type':'application/json'},body:body?JSON.stringify(body):undefined});const x=await r.json();if(!r.ok)throw Object.assign(Error(x.error),{status:r.status});return x;};
const date=x=>x?new Date(x).toLocaleString():'Not applicable — no paid subscription';
const act=fn=>async e=>{e?.preventDefault();const b=e?.target?.querySelector?.('button')||e?.target;if(b)b.disabled=true;feedback.textContent='';try{await fn(e);}catch(err){feedback.textContent=err.message;}finally{if(b)b.disabled=false;}};
function auth(email){root.innerHTML=`<section class="card"><h2>Welcome to your members area</h2><p>Create a separate membership login for the private preview. Existing bookings and newsletter preferences stay as they are.</p><form id="signup"><h3>Create your account</h3><label for="name">Name</label><input id="name" name="name" autocomplete="name" required><label for="email">Email</label><input id="email" name="email" type="email" value="${esc(email)}" autocomplete="email" required><label for="new-password">Password (at least 12 characters)</label><input id="new-password" name="member_password" type="password" minlength="12" maxlength="200" autocomplete="new-password" required><div class="hp" aria-hidden="true"><label>Website<input name="website" tabindex="-1" autocomplete="off"></label></div><div class="actions"><button>Create account &amp; send confirmation</button></div></form></section><section class="card"><form id="login"><h2>Already registered?</h2><label for="login-email">Email</label><input id="login-email" name="email" type="email" value="${esc(email)}" autocomplete="username" required><label for="login-password">Password</label><input id="login-password" name="member_password" type="password" autocomplete="current-password" required><div class="actions"><button>Sign in</button><button type="button" id="forgot">Send password reset</button></div></form></section>`;
for(const id of ['signup','login'])document.getElementById(id).onsubmit=act(async e=>{const x=await api(id,'POST',Object.fromEntries(new FormData(e.target)));await load();feedback.textContent=x.message||'Signed in.';});
document.getElementById('forgot').onclick=act(async()=>{feedback.textContent=(await api('forgot','POST',{email:document.getElementById('login-email').value})).message;});}
function account(m){root.innerHTML=`<section class="card"><h2>Hello, ${esc(m.name)}</h2><dl><dt>Email</dt><dd>${esc(m.email)}</dd><dt>Email confirmed</dt><dd>${m.verified?'Yes':'Not yet'}</dd><dt>Membership tier</dt><dd>Shared membership preview — tier not selected</dd><dt>Status</dt><dd>${esc(m.status.replaceAll('_',' '))}</dd><dt>Access through</dt><dd>${date(m.access_until)}</dd><dt>Billing period start</dt><dd>${date(m.billing_period_start)}</dd><dt>${m.cancel_at_period_end?'Cancellation effective':'Next billing date / period end'}</dt><dd>${date(m.billing_period_end)}</dd></dl>${m.cancel_at_period_end?'<p>Cancellation is scheduled. Access continues through the end of your paid period.</p>':''}<p class="note">Preview access is not a paid subscription. Tier benefits and pricing await Christina’s confirmation.</p><div class="actions">${!m.verified?'<button id="resend">Resend confirmation email</button>':''}<button id="portal">Manage billing / cancel</button><button id="reset">Send password reset</button><button id="logout">Sign out</button></div><p class="muted">${m.portal_available?'Billing management opens securely in Stripe’s sandbox.':'Stripe sandbox billing is not connected yet. This preview cannot create live charges.'}</p></section>`;
if(!m.verified)document.getElementById('resend').onclick=act(async()=>feedback.textContent=(await api('resend','POST',{})).message);
document.getElementById('portal').onclick=act(async()=>{const x=await api('portal','POST',{});location.assign(x.url);});document.getElementById('reset').onclick=act(async()=>feedback.textContent=(await api('forgot','POST',{email:m.email})).message);document.getElementById('logout').onclick=act(async()=>{await api('logout','POST',{});await load();});}
async function load(){const page=location.pathname.split('/').pop();if(['verify','reset'].includes(page)){const t=new URLSearchParams(location.search).get('token');history.replaceState(null,'',location.pathname);root.innerHTML=`<section class="card"><h2>${page==='verify'?'Confirm your member account':'Choose a new password'}</h2><form id="token-form">${page==='reset'?'<label for="reset-password">New password (at least 12 characters)</label><input id="reset-password" type="password" minlength="12" maxlength="200" autocomplete="new-password" required>':'<p>Confirm to activate your private preview. No payment is required.</p>'}<div class="actions"><button>${page==='verify'?'Confirm my account':'Save new password'}</button></div></form><p><a href="/members">Back to members</a> · <a href="/members/review">Open private preview</a></p></section>`;document.getElementById('token-form').onsubmit=act(async()=>{const x=await api(page,'POST',{token:t,member_password:document.getElementById('reset-password')?.value});feedback.textContent=x.message;document.getElementById('token-form').hidden=true;});return;}
const config=await api('config');if(page==='information'){root.innerHTML=`<section class="card"><h2>Monthly astrology, in one quiet place</h2><p>Read monthly horoscopes for all twelve zodiac signs. Explore your Sun, Moon, and Rising signs, or spend time with any sign that interests you.</p><p>New monthly content is written and published by Christina. Drafts remain private until she publishes them to members.</p><div class="grid"><section><h3>Tier 1</h3><p>Final name, benefits, and pricing to be confirmed.</p></section><section><h3>Tier 2</h3><p>Final name, benefits, and pricing to be confirmed.</p></section></div><p class="note">This is a private information-page draft. Enrollment and checkout are disabled. No membership price or additional benefit is promised here.</p><p>Planned account features include secure billing management, cancellation through Stripe, and access through the end of a paid period.</p></section>`;return;}
let m;try{m=await api('me');}catch(e){if(e.status!==401)throw e;auth(config.testEmail);return;}
if(page==='account'||!m.access){account(m);return;}
const months=await api('horoscopes');root.innerHTML=`<section class="card"><h2>Your monthly horoscopes</h2><p>Every sign is yours to explore. Start with your Sun, Moon, or Rising.</p><label for="month">Choose a month</label><select id="month">${months.map(x=>`<option value="${x.month}">${esc(x.title)}${x.demo?' — demonstration':''}</option>`).join('')}</select>${!months.length?'<p>No month has been published yet. Christina can add a demonstration month in Admin → Membership.</p>':''}</section><div id="readings"></div>`;
const show=()=>{const x=months.find(x=>x.month===document.getElementById('month').value);if(!x)return;document.getElementById('readings').innerHTML=`${x.demo?'<p class="note">DEMONSTRATION CONTENT — for interface review only. These are not actual monthly forecasts.</p>':''}<nav class="signs" aria-label="Zodiac signs">${config.signs.map(s=>`<a href="#sign-${s}">${s}</a>`).join('')}</nav>${config.signs.map(s=>`<article class="card" id="sign-${s}"><h2>${s}</h2><div class="horoscope">${esc(x.content[s])}</div><p><a href="#month">Back to month selector</a></p></article>`).join('')}`;};document.getElementById('month').onchange=show;show();}
load().catch(e=>{feedback.textContent=e.message;root.innerHTML='<section class="card"><a class="button" href="/members/review">Open private preview with Admin</a></section>';});
})();
